apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-demo-crdp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-demo-crdp
  template:
    metadata:
      labels:
        app: crypto-demo-crdp
    spec:
      containers:
      - name: crypto-demo-crdp
        image: crypto-demo-crdp:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9001
---
apiVersion: v1
kind: Service
metadata:
  name: crypto-app-service
spec:
  selector:
    app: crypto-demo-crdp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9001
  type: NodePort
